/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.memmorise.app;

import org.junit.jupiter.api.Test;

class MemoriseStarterTest {
    @Test
    void appHasAGreeting() {

    }
}
